### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by nikeee**
All existing contributors must consent to this change.

Just reply with `:+1:` and we can merge this.
- @flxai
- @jplatte
- @phlmn
- @Aluhut
- @soerface
- @nikeee
- @cfstras

### CODE REVIEW

**Comment by nikeee** [comment]
:+1:

**Comment by cfstras** [comment]
:+1:

**Comment by soerface** [comment]
[My contribution](https://github.com/flipdot/drinks-storage-mqtt/commits?author=soerface) is insignificant, so I abstain from voting.

**Comment by phlmn** [comment]
👍

**Comment by jplatte** [comment]
:+1:

**Comment by flxai** [comment]
Following the reasoning behind the related issue in [`drinks-storage-state`](https://github.com/flipdot/drinks-storage-state/pull/1)

> Why AGPL if https://github.com/flipdot/drinks-storage-order has 0BSD?

I'd prefer for all `drinks-storage-*` projects to use 0BSD if any license.

**Pull request merged**
